version: "3.1"
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./.docker/metabase-data:/metabase-data
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: docker
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: api_vendas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      PGDATA: /var/lib/postgresql/data
