version: "3.8"
services:
  pgadmin:
    container_name: api-vendas_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: docker
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    depends_on:
      - postgres

  postgres:
    container_name: api-vendas_postgres
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: api_vendas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      PGDATA: /var/lib/postgresql/data

  redis:
    container_name: api-vendas_redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  redisinsight:
    container_name: api-vendas_redisinsight
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis

volumes:
  postgres-data:
  pgadmin-data:
  redis-data:
  redisinsight-data:
